server:
  port: 8088

spring:
  application:
    name: notification

  datasource:
    url: jdbc:mysql://localhost:3306/food_order_db
    username: food_order
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        hbm2ddl:
          auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
